### ISSUE TITLE
Datatable 관련 문제

### ISSUE THREAD

**Issue by dmek29** [jht3820/luna-agile#103]
### Steps 
 Datatable 생성 시 문제
1. datatable columns 이상
2. row 생성 후 템플릿 변경 시 문제 발생

### Description :
1. column 이상
   : datatable column 옵션 중 autoHide가 true로 선언된 항목이 하나라도 있을 경우 datatable에서 생략되는
     컬럼이 없어도 불필요한 detail(▶) 버튼이 나타남

2. row 이상
   : row가 그려진 후에 탬플릿을 변경하면 row에 있는 액션버튼 동작이 이뤄지지 않음

**Comment by jht3820** [comment]
datatable  컬럼, row 이상 문제 수정
: core 확인
