### ISSUE TITLE
데이터 테이블 기능 추가 요청

### ISSUE THREAD

**Issue by shopcjkwm** [jht3820/luna-agile#104]
### 기존 기능의 문제점
1. 현재는 데이터 테이블의 헤더를 숨길 수 없음
2. 데이터 테이블의 검색 조건이 컬럼을 기준으로 생성됨, 별도로 생성할 수 있어야 함

### 새로운 기능 제안
1. 화면에 따라 데이터 테이블의 헤더가 보여지거나 보여지지 않아야 될 경우가 존재함
   데이터 테이블 생성 시 별도 옵션을 주어 헤더를 표시하거나 표시하지 않도록 할 수 있어야 함

2. 데이터 테이블 검색 옵션은 데이터 테이블 컬럼에 지정함, 검색 조건이 컬럼 기준으로 되어버리므로
    별도의 검색 조건을 추가 할 수 있어야 함

**Comment by jht3820** [comment]
1. 데이터 테이블의 헤더 숨길 수 있는 기능 추가
2. 데이터 테이블의 검색조건을 별도로 생성할 수 있도록 수정

- core 확인
