### ISSUE TITLE
일부 화면 IE에서 동작이상 문제

### ISSUE THREAD

**Issue by hyungyeongoh** [jht3820/luna-agile#64]
### Steps 
일부 화면 IE에서 동작이상 문제

### Description :
메뉴의 권한을 부여하는 화면 - 업무역할 관리, 메뉴 및 권한관리에서 체크박스 동작에 문제 있습니다.
전체 체크의 경우 크롬에서는 정상 동작하나 IE에서는 동작 이상이 발생합니다.

**Comment by jht3820** [comment]
IE 동작이상 수정완료
